name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "1 1 * * 1"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-androidsdk@v3
        with:
          android-version: 33
          android-tools: latest

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --enable-native-access=ALL-UNNAMED

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: APK
          path: app/build/outputs/apk/release/*.apk
